# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72cbd9378f2dd30209d37b516202c2d1ea27c458c529eeefafbb0d6c8a97525719adc40c7a017f1548fbaa71326122c989df9822aa27aba605b7719aff22b031

test:
  secret_key_base: db64950db4fd2ac7913399747adbf0efb6ff9c4cff627ac38d91dee45f5e62bd2b24d94f85643f6dd7bc4aecbf3add80be10f4938a44482a68acafb0ac1e389d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
